[project]
name = "pythonpackagetemplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.0.1",
    "pyre-check>=0.9.23",
    "ruff>=0.8.0",
]
